#!/usr/bin/env sh
export EDITOR='nvim';

export FZF_DEFAULT_COMMAND='rg --files';

export HISTSIZE='32768';
export HISTFILESIZE="${HISTSIZE}";
export HISTCONTROL='ignoreboth';

export MANPAGER='less -X';

##############################################################
#
#          配置远程连接导致的中文显示编码问题
#
##############################################################
export LANG='en_US.UTF-8';
export LC_ALL='en_US.UTF-8';


