#!/usr/bin/env sh
# 路径相关,主要是用来引入bin文件

# use gnu instead unix
if type brew &>/dev/null; then
  HOMEBREW_PREFIX=$(brew --prefix)
  for d in ${HOMEBREW_PREFIX}/opt/*/libexec/gnubin; do
    if [[ ${d} != *"libtool"* ]];then
      export PATH=$d:$PATH; 
    fi
  done
fi
# 本地 命令
export PATH="$HOME/Cystem/bin:$PATH"

# older software
# export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
# export PATH="/usr/local/opt/llvm/bin:$PATH"
# export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"
# export PATH="/usr/local/sbin:$PATH"
# export PATH="/usr/local/opt/curl/bin:$PATH"

# === flutter
export PATH="$HOME/Cystem/flutter/bin;$PATH"
# === rvm
export PATH="$HOME/.rvm/bin:$PATH"
# === java
export PATH="$HOME/.jenv/bin:$PATH"
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
# === java android
export ANDROID_HOME="$HOME/Software/AndroidSDK"
export ANDROID_TOOLS=$ANDROID_HOME/tools
export ANDROID_PLATFORM_TOOLS=$ANDROID_HOME/platform-tools
export ANDROID_BUILD_TOOLS=$ANDROID_HOME/build-tools/30.0.2
export PATH="$PATH:$ANDROID_HOME/tools"
export PATH="$PATH:$ANDROID_HOME/tools/bin"
export PATH="$PATH:$ANDROID_PLATFORM_TOOLS"
export PATH="$PATH:$ANDROID_HOME/emulator"

# === golang
export GO111MODULE=on
export GOPROXY="https://goproxy.cn,direct"
export GOPATH=$HOME/.go
export GOROOT=/opt/homebrew/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# JavaScript / NodeJS
export NODE_REPL_HISTORY=~/.node_history;
export NODE_REPL_HISTORY_SIZE='32768';
export NODE_REPL_MODE='sloppy';
export PATH="$HOME/.yarn/bin:$PATH"

# Ruby
export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.0/bin:$PATH"
